// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC_nDb9ovk1i6dn7zGnRy3q_KZqTF6F84k',
    appId: '1:774616192127:web:aabbe828fd2ba523ab5b4a',
    messagingSenderId: '774616192127',
    projectId: 'flutter-app-5414c',
    authDomain: 'flutter-app-5414c.firebaseapp.com',
    storageBucket: 'flutter-app-5414c.appspot.com',
    measurementId: 'G-9JW8Y28GYB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBugiZ4ckfGch98DUxYRChTvcMxKEZSBtg',
    appId: '1:774616192127:android:3eaed6e21db9963eab5b4a',
    messagingSenderId: '774616192127',
    projectId: 'flutter-app-5414c',
    storageBucket: 'flutter-app-5414c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA-IdAu_gMN6cMK7Y4GLVmnt9BEWUGNsqE',
    appId: '1:774616192127:ios:e29738a244584cc8ab5b4a',
    messagingSenderId: '774616192127',
    projectId: 'flutter-app-5414c',
    storageBucket: 'flutter-app-5414c.appspot.com',
    androidClientId: '774616192127-0e9fat0guq35i1tm2ertaqik52j19po7.apps.googleusercontent.com',
    iosClientId: '774616192127-muu7qkqbm9acc99v3jin0dr0qmle8gnp.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterAuth',
  );
}
